### ISSUE TITLE
Missing CSV/TSV writers for SPARQL results

### ISSUE THREAD

**Issue by namedgraph** [AtomGraph/LinkedDataHub#176]
CSV fails:
```
curl 'https://linkeddatahub.com/demo/northwind-traders/sparql?query=select%20*%0A%7B%0A%3Fs%20%3Fp%20%3Fo%0A%7D' -H 'User-Agent: python urllib/3.3.0' -H "Accept: text/csv"
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Internal Server Error</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.59</h3></body></html>%    
```
TSV fails:
```
curl 'https://linkeddatahub.com/demo/northwind-traders/sparql?query=select%20*%0A%7B%0A%3Fs%20%3Fp%20%3Fo%0A%7D' -H 'User-Agent: python urllib/3.3.0' -H "Accept: text/tab-separated-values"
<!doctype html><html lang="en"><head><title>HTTP Status 500 – Internal Server Error</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 500 – Internal Server Error</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Internal Server Error</p><p><b>Description</b> The server encountered an unexpected condition that prevented it from fulfilling the request.</p><hr class="line" /><h3>Apache Tomcat/9.0.59</h3></body></html>% 
```
XML works:
```
curl 'https://linkeddatahub.com/demo/northwind-traders/sparql?query=select%20*%0A%7B%0A%3Fs%20%3Fp%20%3Fo%0A%7D' -H 'User-Agent: python urllib/3.3.0' -H "Accept: application/sparql-results+xml"
<?xml version="1.0"?>
<sparql xmlns="http://www.w3.org/2005/sparql-results#">
  <head>
    <variable name="s"/>
    <variable name="p"/>
    <variable name="o"/>
  </head>
  <results>
  </results>
</sparql>
```

**Comment by namedgraph** [comment]
However it works on KGDN which runs a newer LDH version 🤷‍♂️ 
```
curl 'https://kgdev.net/sparql?query=select%20*%0A%7B%0A%3Fs%20%3Fp%20%3Fo%0A%7D' -H 'User-Agent: python urllib/3.3.0' -H "Accept: text/csv"
```

**Comment by namedgraph** [comment]
Hmm this is really weird... Using Python code I still get exceptions with `Accept: text/csv`:
```python
from urllib.error import HTTPError
import urllib.request
req = urllib.request.Request('https://kgdev.net/sparql?query=select%20*%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D')
req.add_header('Accept', 'test/csv')

with urllib.request.urlopen(req) as response:
    try:
        data = response.read()
        print(data)
    except HTTPError as err:
        print(err.req)
```
```
Traceback (most recent call last):
  File "/Users/Martynas.Jusevicius/WebRoot/sparql-langchain/main.py", line 68, in <module>
    with urllib.request.urlopen(req) as response:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.3/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error
```
But not with `application/sparql-results+xml`:
```python
from urllib.error import HTTPError
import urllib.request
req = urllib.request.Request('https://kgdev.net/sparql?query=select%20*%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D')
req.add_header('Accept', 'application/sparql-results+xml')

with urllib.request.urlopen(req) as response:
    try:
        data = response.read()
        print(data)
    except HTTPError as err:
        print(err.req)
```
```
b'<?xml version="1.0"?>\n<sparql xmlns="http://www.w3.org/2005/sparql-results#">\n  <head>\n    <variable name="s"/>\n    <variable name="p"/>\n    <variable name="o"/>\n  </head>\n  <results>\n  </results>\n</sparql>\n'
```
