### ISSUE TITLE
Application not found + Ontology cannot be null errors while attempting to access service launched on Ubuntu host

### ISSUE THREAD

**Issue by osharper** [AtomGraph/LinkedDataHub#28]
Setup is basically the same as in the [previous issue](https://github.com/AtomGraph/LinkedDataHub/issues/27). All docker based services seem to start normally (the only issue is service startup time `Server startup in 339410 ms`, not sure why it is so big and whether it's fine) but when one tries to access the launched app via browser (Firefox) with generated `owner.p12` certificate, the following error occurs and browser ending up with displaying a blank page.

Docker logs:
```
Attaching to linkeddatahub_fuseki-admin_1, linkeddatahub_linkeddatahub_1, linkeddatahub_fuseki-end-user_1, linkeddatahub_nginx_1, linkeddatahub_email-server_1
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO  Apache Jena Fuseki 3.13.0
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO  Configuration file /var/fuseki/config.ttl
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO  Path = /ds; Services = [""=>gsp-rw, ""=>query, ""=>update]
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO    Memory: 483.4 MiB
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO    Java:   1.8.0_111
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO    OS:     Linux 4.15.0-55-generic amd64
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:28] Server     INFO    PID:    1
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:29] Server     INFO  Start Fuseki (port=3030)
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:36] Fuseki     INFO  [1] GET http://fuseki-admin:3030/ds/
[33mlinkeddatahub_1    |[0m ### Generating server certificate
[33mlinkeddatahub_1    |[0m 
[33mlinkeddatahub_1    |[0m ### Quad store URL of the root admin service: http://fuseki-admin:3030/ds/
[33mlinkeddatahub_1    |[0m 
[33mlinkeddatahub_1    |[0m ### Loading default datasets into the end-user/admin triplestores...
[33mlinkeddatahub_1    |[0m ### URL http://fuseki-end-user:3030/ds/ responded
[33mlinkeddatahub_1    |[0m   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[33mlinkeddatahub_1    |[0m                                  Dload  Upload   Total   Spent    Left  Speed
[33mlinkeddatahub_1    |[0m 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 46107    0    64  100 46043     90  64932 --:--:-- --:--:-- --:--:-- 64940
100 46108    0    65  100 46043     90  64348 --:--:-- --:--:-- --:--:-- 64305
[33mlinkeddatahub_1    |[0m { 
[33mlinkeddatahub_1    |[0m   "count" : 207 ,
[33mlinkeddatahub_1    |[0m   "tripleCount" : 0 ,
[33mlinkeddatahub_1    |[0m   "quadCount" : 207
[33mlinkeddatahub_1    |[0m }
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO  Apache Jena Fuseki 3.13.0
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO  Configuration file /var/fuseki/config.ttl
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO  Path = /ds; Services = [""=>gsp-rw, ""=>query, ""=>update]
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO    Memory: 483.4 MiB
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO    Java:   1.8.0_111
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO    OS:     Linux 4.15.0-55-generic amd64
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:28] Server     INFO    PID:    1
[35mnginx_1            |[0m ### Waiting for linkeddatahub...
[35mnginx_1            |[0m ### linkeddatahub responded
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:29] Server     INFO  Start Fuseki (port=3030)
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:34] Fuseki     INFO  [1] GET http://fuseki-end-user:3030/ds/
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:35] Fuseki     INFO  [1] 200 OK (474 ms)
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:35] Fuseki     INFO  [2] GET http://fuseki-end-user:3030/ds/
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:35] Fuseki     INFO  [2] 200 OK (186 ms)
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:35] Fuseki     INFO  [3] POST http://fuseki-end-user:3030/ds/
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:35] Fuseki     INFO  [3] Body: Content-Length=46043, Content-Type=application/n-quads, Charset=null => N-Quads : Count=207 Triples=0 Quads=207
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:36] Fuseki     INFO  [3] 200 OK (701 ms)
[31memail-server_1     |[0m + sed -ri '
[31memail-server_1     |[0m 	s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
[31memail-server_1     |[0m 	s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
[31memail-server_1     |[0m 	s/^#?(dc_relay_nets)=.*/\1='\''172.19.0.3\/16'\''/;
[31memail-server_1     |[0m 	s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
[31memail-server_1     |[0m ' /etc/exim4/update-exim4.conf.conf
[31memail-server_1     |[0m + update-exim4.conf -v
[31memail-server_1     |[0m using non-split configuration scheme from /etc/exim4/exim4.conf.template
[31memail-server_1     |[0m     1 LOG: MAIN
[31memail-server_1     |[0m     1   exim 4.92 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv4)
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:40] Fuseki     INFO  [1] 200 OK (3.585 s)
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:40] Fuseki     INFO  [2] GET http://fuseki-admin:3030/ds/
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:42] Fuseki     INFO  [2] 200 OK (2.332 s)
[33mlinkeddatahub_1    |[0m ### URL http://fuseki-admin:3030/ds/ responded
[33mlinkeddatahub_1    |[0m   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
[33mlinkeddatahub_1    |[0m                                  Dload  Upload   Total   Spent    Left  Speed
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:42] Fuseki     INFO  [3] POST http://fuseki-admin:3030/ds/
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:43] Fuseki     INFO  [3] Body: Content-Length=547638, Content-Type=application/n-quads, Charset=null => N-Quads : Count=2392 Triples=0 Quads=2392
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:43] Fuseki     INFO  [3] 200 OK (1.077 s)
[33mlinkeddatahub_1    |[0m 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  534k    0     0  100  534k      0   527k  0:00:01  0:00:01 --:--:--  527k
100  534k    0    67  100  534k     61   487k  0:00:01  0:00:01 --:--:--  487k
[33mlinkeddatahub_1    |[0m { 
[33mlinkeddatahub_1    |[0m   "count" : 2392 ,
[33mlinkeddatahub_1    |[0m   "tripleCount" : 0 ,
[33mlinkeddatahub_1    |[0m   "quadCount" : 2392
[33mlinkeddatahub_1    |[0m }
[33mlinkeddatahub_1    |[0m openjdk version "1.8.0_181"
[33mlinkeddatahub_1    |[0m OpenJDK Runtime Environment (build 1.8.0_181-8u181-b13-1~deb9u1-b13)
[33mlinkeddatahub_1    |[0m OpenJDK 64-Bit Server VM (build 25.181-b13, mixed mode)
[33mlinkeddatahub_1    |[0m      intx CompilerThreadStackSize                   = 0                                   {pd product}
[33mlinkeddatahub_1    |[0m     uintx ErgoHeapSizeLimit                         = 0                                   {product}
[33mlinkeddatahub_1    |[0m     uintx HeapSizePerGCThread                       = 87241520                            {product}
[33mlinkeddatahub_1    |[0m     uintx InitialHeapSize                          := 33554432                            {product}
[33mlinkeddatahub_1    |[0m     uintx LargePageHeapSizeThreshold                = 134217728                           {product}
[33mlinkeddatahub_1    |[0m     uintx MaxHeapSize                              := 524288000                           {product}
[33mlinkeddatahub_1    |[0m      intx ThreadStackSize                           = 1024                                {pd product}
[33mlinkeddatahub_1    |[0m      intx VMThreadStackSize                         = 1024                                {pd product}
[33mlinkeddatahub_1    |[0m ### Waiting for http://fuseki-end-user:3030/ds/...
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:43] Fuseki     INFO  [4] GET http://fuseki-end-user:3030/ds/
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:44] Fuseki     INFO  [4] 200 OK (173 ms)
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:44] Fuseki     INFO  [5] GET http://fuseki-end-user:3030/ds/
[32mfuseki-end-user_1  |[0m [2020-01-28 16:00:44] Fuseki     INFO  [5] 200 OK (112 ms)
[33mlinkeddatahub_1    |[0m ### URL http://fuseki-end-user:3030/ds/ responded
[33mlinkeddatahub_1    |[0m ### Waiting for http://fuseki-admin:3030/ds/...
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:44] Fuseki     INFO  [4] GET http://fuseki-admin:3030/ds/
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:46] Fuseki     INFO  [4] 200 OK (2.190 s)
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:46] Fuseki     INFO  [5] GET http://fuseki-admin:3030/ds/
[36mfuseki-admin_1     |[0m [2020-01-28 16:00:47] Fuseki     INFO  [5] 200 OK (1.391 s)
[33mlinkeddatahub_1    |[0m ### URL http://fuseki-admin:3030/ds/ responded
[33mlinkeddatahub_1    |[0m ### Waiting for nginx...
[33mlinkeddatahub_1    |[0m ### Host nginx responded
[33mlinkeddatahub_1    |[0m Listening for transport dt_socket at address: 8000
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.909 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.53
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.920 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Jun 29 2018 14:42:45 UTC
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.921 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.53.0
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.922 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.923 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-55-generic
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.924 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.925 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/lib/jvm/java-8-openjdk-amd64/jre
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.927 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_181-8u181-b13-1~deb9u1-b13
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.928 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.929 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.930 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.932 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.935 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.936 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.937 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.939 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.940 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Duser.timezone=Europe/Copenhagen
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.941 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.943 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.945 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.947 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.948 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.2.17 using APR version 1.5.2.
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.950 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:49.964 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.1.0f  25 May 2017)
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:50.272 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:50.313 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:50.400 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8443"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:51.698 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:51.710 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 3387 ms
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:51.803 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:51.807 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.53
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:00:51.855 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deploying configuration descriptor /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:01:00.588 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
[35mnginx_1            |[0m 195.231.4.32 - - [28/Jan/2020:16:04:54 +0000] "GET login.cgi HTTP/1.1" 400 157 "-" "-"
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:30.989 WARNING [localhost-startStop-1] org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [330,040] milliseconds.
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:31.054 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDescriptor Deployment of configuration descriptor /usr/local/tomcat/conf/Catalina/localhost/ROOT.xml has finished in 339,196 ms
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:31.063 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:31.107 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:31.114 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8443"]
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:06:31.122 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 339410 ms
[35mnginx_1            |[0m 161.142.234.65 [28/Jan/2020:16:14:43 +0000] TCP [] [upstream_server_https] 200 1416 7 6.556
[35mnginx_1            |[0m 161.142.234.65 [28/Jan/2020:16:14:43 +0000] TCP [] [upstream_server_https] 200 1416 7 6.315
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:14:50.068 INFO [http-nio-8443-exec-9] com.sun.jersey.server.impl.application.WebApplicationImpl._initiate Initiating Jersey application, version 'Jersey: 1.19 02/11/2015 03:25 AM'
[35mnginx_1            |[0m 161.142.234.65 [28/Jan/2020:16:14:55 +0000] TCP [] [upstream_server_https] 200 1467 1422 5.953
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:15:01.694 INFO [http-nio-8443-exec-9] com.sun.jersey.server.impl.application.DeferredResourceConfig$ApplicationHolder.<init> Instantiated the Application class com.atomgraph.linkeddatahub.Application
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:15:04.309 SEVERE [http-nio-8443-exec-9] com.sun.jersey.spi.container.ContainerResponse.mapException Exception mapper com.atomgraph.server.mapper.NotFoundExceptionMapper@45cf1f83 for Throwable com.atomgraph.core.exception.NotFoundException: Application not found threw a RuntimeException when attempting to obtain the response
[33mlinkeddatahub_1    |[0m 28-Jan-2020 17:15:04.315 SEVERE [http-nio-8443-exec-9] com.sun.jersey.spi.container.ContainerResponse.logException Mapped exception to response: 500 (Internal Server Error)
[33mlinkeddatahub_1    |[0m  java.lang.IllegalArgumentException: Ontology cannot be null
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.processor.util.TemplateMatcher.match(TemplateMatcher.java:229)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.processor.util.TemplateMatcher.match(TemplateMatcher.java:137)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateProvider.getTemplate(TemplateProvider.java:77)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateProvider.getTemplate(TemplateProvider.java:72)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateProvider.getContext(TemplateProvider.java:67)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateProvider.getContext(TemplateProvider.java:37)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateCallProvider.getTemplate(TemplateCallProvider.java:97)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateCallProvider.getTemplateCall(TemplateCallProvider.java:73)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateCallProvider.getContext(TemplateCallProvider.java:68)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.provider.TemplateCallProvider.getContext(TemplateCallProvider.java:38)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.mapper.ExceptionMapperBase.getTemplateCall(ExceptionMapperBase.java:164)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.mapper.ExceptionMapperBase.getResponseBuilder(ExceptionMapperBase.java:102)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.mapper.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:35)
[33mlinkeddatahub_1    |[0m 	at com.atomgraph.server.mapper.NotFoundExceptionMapper.toResponse(NotFoundExceptionMapper.java:29)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.spi.container.ContainerResponse.mapException(ContainerResponse.java:480)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1479)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
[33mlinkeddatahub_1    |[0m 	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
[33mlinkeddatahub_1    |[0m 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[33mlinkeddatahub_1    |[0m 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.filters.HttpHeaderSecurityFilter.doFilter(HttpHeaderSecurityFilter.java:126)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:94)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:492)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:620)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
[33mlinkeddatahub_1    |[0m 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:502)
[33mlinkeddatahub_1    |[0m 	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1152)
[33mlinkeddatahub_1    |[0m 	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684)
[33mlinkeddatahub_1    |[0m 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1539)
[33mlinkeddatahub_1    |[0m 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1495)
[33mlinkeddatahub_1    |[0m 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[33mlinkeddatahub_1    |[0m 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[33mlinkeddatahub_1    |[0m 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
[33mlinkeddatahub_1    |[0m 	at java.lang.Thread.run(Thread.java:748)
[33mlinkeddatahub_1    |[0m 
[35mnginx_1            |[0m 161.142.234.65 [28/Jan/2020:16:15:04 +0000] TCP [] [upstream_server_https] 200 1730 1789 15.191
```

**Comment by namedgraph** [comment]
Are you trying to access it on a host different than `localhost`?

**Comment by osharper** [comment]
Yes, exactly. I have a separate host Ubuntu vm and trying to access it from outside. For http part it all seems fine, browser can reach nginx and auth certificate is requested but after that thing go wrong as could be seen by the logs

**Comment by namedgraph** [comment]
OK, got it. This is a legit use case of course; it should be supported now after some refactoring.
The error is misleading, it happens when no application matches the base URI.

Please see the updated configuration: https://github.com/AtomGraph/LinkedDataHub#configuration
After you change `.env` and `config/system.trig`, do this again

    docker-compose down -v && sudo rm -rf certs && git pull && docker-compose pull && docker-compose up

You will need to reinstall the `owner.p12`.

It works locally but I haven't tested on our EC2 Ubuntu yet - will do later today.

**Comment by namedgraph** [comment]
@osharper I have since renamed config properties: `PROXY_HTTP_PORT -> HTTP_PORT`, `PROXY_HTTPS_PORT -> HTTPS_PORT`.

**Comment by namedgraph** [comment]
Runs on EC2 Ubuntu following the latest "Getting started": https://ec2-54-235-229-141.compute-1.amazonaws.com/linkeddatahub/

@osharper please confirm whether it solves the problem for you.

**Comment by osharper** [comment]
yeah, thanks, this issue is now fixed
